<?php

/**
 * PlugintdImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdVisualFactoryPlugin
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PlugintdImage extends BasetdImage
{
  public function postSave($event)
  {
    $sf_upload_dir = sfConfig::get('td_visual_factory_image_dir');
    foreach(sfConfig::get('td_visual_factory_sizes') as $size)
    {
      VisualFactory::Resize(
        sfConfig::get('td_visual_factory_mode'),
        $sf_upload_dir.'/'.$this->getFile(),
        $sf_upload_dir.'/'.$size.'/'.$this->getFile(),
        $size);
    }
  }

  public function postDelete($event)
  {
    $sf_upload_dir = sfConfig::get('td_visual_factory_image_dir');
    foreach(sfConfig::get('td_visual_factory_sizes') as $size)
    {
      unlink($sf_upload_dir.'/'.$size.'/'.$this->getFile());
    }
  }

//  public function preUpdate($event)
//  { // nie działa...
//      var_dump($this->isNew());
//    if (! $this->isNew())
//    {
//      $sf_upload_dir = sfConfig::get('td_visual_factory_image_dir');
//      foreach(sfConfig::get('td_visual_factory_sizes') as $size)
//      {
//        unlink($sf_upload_dir.'/'.$size.'/'.$this->getFile());
//      }
//    }
//  }

  public function postUpdate($event)
  {
    $sf_upload_dir = sfConfig::get('td_visual_factory_image_dir');
    foreach(sfConfig::get('td_visual_factory_sizes') as $size)
    {
      VisualFactory::Resize(
        sfConfig::get('td_visual_factory_mode'),
        $sf_upload_dir.'/'.$this->getFile(),
        $sf_upload_dir.'/'.$size.'/'.$this->getFile(),
        $size);
    }
  }
}