<?php

/**
 * PlugintdImageAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdVisualFactoryPlugin
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PlugintdImageAlbum extends BasetdImageAlbum
{
  /**
   * Returns short description of the image album.
   *
   * @return String - short description.
   */
  public function getDescriptionShort()
  {
    return tdTools::getMbShortenedString($this->getDescription(), sfConfig::get('td_short_text_sign_count'));
  }

  /**
   * Activates the image album.
   *
   * @return True
   */
  public function activate()
  {
    $this->setActive(true);
    $this->save();
    return true;
  }

  /**
   * Deactivates the image album.
   *
   * @return True
   */
  public function deactivate()
  {
    $this->setActive(false);
    $this->save();
    return true;
  }

  /**
   * Deletes all image records before the whole image album is deleted.
   *
   * @param Doctrine_Event $event
   */
  public function preDelete($event)
  {
    foreach($this->getImages() as $image)
      $image->delete();
  }
}