<?php

/**
 * PlugintdWatermarkTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    tdVisualFactoryPlugin
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class PlugintdWatermarkTable extends Doctrine_Table
{

}