td_sample_image:
  url:   /image
  param: { module: tdSampleImage, action: index }

td_sample_image_show:
  url:   /image/:id
  param: { module: tdSampleImage, action: show }

# ajax actions

ajax_image_activate:
  url:   /ajax-image-activate/:id
  param: { module: td_image_album, action: activate }
  requirements:
    id: \d+

ajax_image_deactivate:
  url:   /ajax-image-deactivate/:id
  param: { module: td_image_album, action: deactivate }
  requirements:
    id: \d+

td_image:
  class: sfDoctrineRouteCollection
  options:
    model:                tdImage
    module:               td_image
    prefix_path:          /td_image
    column:               id
    with_wildcard_routes: true

td_image_album:
  class: sfDoctrineRouteCollection
  options:
    model:                tdImageAlbum
    module:               td_image_album
    prefix_path:          /td_image_album
    column:               id
    with_wildcard_routes: true

td_watermark:
  class: sfDoctrineRouteCollection
  options:
    model:                tdWatermark
    module:               td_watermark
    prefix_path:          /td_watermark
    column:               id
    with_wildcard_routes: true
