generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tdWatermark
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          td_watermark
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing
    i18n_catalogue:        sf_admin

    config:
      actions: ~
      fields:
        file:
          label: Plik
        name:
          label: Nazwa
        description:
          label: Opis
      list:
        title: List of watermarks
        display: [ name, description, updated_at ]
      filter: ~
      form:
        fields:
          name:
            attributes: { size: 80 }
          description:
            attributes: { cols: 80, rows: 3 }
      edit:
        title: Edit watermark
      new:
        title: New watermark
